name: Beta Release to Github Pages (GAVFU)

on:
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'gavfu/crust-files'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - name: Build
        run: |
          yarn install
          yarn export

      - name: Deploy Gh-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: files.decoo.cloud
